#https端口号.
server:
  port: 8080
  ssl:
    #证书的路径.
    key-store: classpath:keystore.p12
    #证书密码，请修改为您自己证书的密码.
    key-store-password: changeit
    #秘钥库类型
    keyStoreType: PKCS12
    #证书别名
    keyAlias: tomcat
#    client-auth: need
    key-store-provider: SUN
    trust-store-provider: SUN
file:
  upload-dir: ./upload/
#  servlet:
#    context-path: /java_demo

spring:
  mvc:
    static-path-pattern: /upload/**
  web:
    resources:
      static-locations:
        - file:upload
elasticsearch-rest-client:
    username: elastic
    password: changeme
    servers:
      - 172.16.0.4:9200
